version: '2'
services:
  web:
    build: .
    image: studiogonzagao
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      DB_URI: "mongodb://db/sgonzagao"
      NODE_ENV: "production"
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
  